app:
  host: "127.0.0.1"
  port: 8080

postgres:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "7549"
  dbname: "AvitoPVZ"

jwt:
  secret: dshcwghcjhcygscgdwkejcgdgcjknscshyfgwtgcsdhwjfuihuywegcbsdjcsdcjs