app:
  host: "0.0.0.0"
  port: 8080

postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "7549"
  dbname: "AvitoPVZ"

jwt:
  secret: dshcwghcjhcygscgdwkejcgdgcjknscshyfgwtgcsdhwjfuihuywegcbsdjcsdcjs